name: Dispatch Release Push Public
on:
  workflow_dispatch:

jobs:
  create_release_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Fail if branch is not main
      if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
      run: |
        echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
        exit 1
        
   # - name: Fail if action is run on other repository than darwin-eu-dev
   #   if: github.event_name == 'workflow_dispatch' && env.GITHUB_REPOSITORY_OWNER != 'darwin-eu-dev'
   #   run: |
   #     echo "This workflow should not be triggered on other repositories than darwin-eu-dev"
   #     exit 1 

    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Get Package Name from DESCRIPTION
      id: get_package_name
      run: |
        PACKAGE_NAME=$(grep -E '^Package:' DESCRIPTION | awk '{print $2}')
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

    - name: Use Package Name
      run: echo "The package name is ${{ env.PACKAGE_NAME }}"

    - name: Get Version from DESCRIPTION
      id: get_version
      run: |
        VERSION=$(grep -E '^Version:' DESCRIPTION | awk '{print $2}')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create Release in Source Repository
      id: create_release_source
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: Release of version ${{ env.VERSION }}. For changelog see NEWS.md.
        draft: false
        prerelease: false

    - name: Print
      run: env | sort

    - name: Checkout target repo
      uses: actions/checkout@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: 'Target'
        ref: 'main'
        repository: 'darwin-eu/${{ env.PACKAGE_NAME }}'
        token: ${{ secrets.PRIVATE_TOKEN }}
        persist-credentials: true

    - name: Push to public mirror
      id: push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      working-directory: 'Target'
      run: |
        git config --global user.name PRijnbeek
        git fetch --all
        git reset --hard origin/main
        eval 'git pull https://$GITHUB_TOKEN@github.com/darwin-eu-dev/${{ env.PACKAGE_NAME }}.git main'
        git push origin main

    - name: Create Release in Target Repository
      id: create_release_target
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        owner: darwin-eu
        repo: ${{ env.PACKAGE_NAME }}
        tag_name: v${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: Release of version ${{ env.VERSION }}. For changelog see NEWS.md.
        draft: false
        prerelease: false
